name: Deploy

on:
  push:
    tags: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo login
        run: cargo login
      - name: Cargo publish
        run: cargo publish --verbose
